# Тестовый api
GET http://localhost:8080/api HTTP/1.1
Content-Type: application/json

###

# Предложения по аренде
## Получение списка предложений
GET http://localhost:9000/offers HTTP/1.1
Content-Type: application/json

###
## Получение списка премиальных предложений для города
GET http://localhost:9000/offers/premium/hamburg HTTP/1.1
Content-Type: application/json

###

## Получение предложения по id
GET http://localhost:9000/offers/634ef0047bd6c921c28207a2 HTTP/1.1
Content-Type: application/json

###

## Удаление предложения по id
DELETE http://localhost:9000/offers/6353da8a4594adbfdae292c2 HTTP/1.1
Content-Type: application/json

###

## Редактирование предложения по id
PUT http://localhost:9000/offers/6353db49cd40c487f2da025c HTTP/1.1
Content-Type: application/json

{
  "offerName": "Apartments",
  "description": "Canal View Prinsengracht",
  "date": "2022-05-12T11:56:37.573Z",
  "city": "Paris",
  "preview": "https://i.com/1",
  "photos": ["https://i.com/4", "https://i.com/5"],
  "premium": true,
  "favorite": false,
  "rating": 5,
  "housingType": "House",
  "roomCount": 2,
  "guestCount": 2,
  "price": 2000,
  "conveniences": ["Washer", "Towels"],
  "authorId": "634ef0047bd6c921c2820792",
  "coordinates": {"latitude": "53.550341", "longitude": "4.895168"}
}

###

## Создание предложения
POST http://localhost:9000/offers HTTP/1.1
Content-Type: application/json

{
  "offerName": "Apartments",
  "description": "Canal View Prinsengracht",
  "date": "2022-05-12T11:56:37.573Z",
  "city": "Paris",
  "preview": "https://i.com/1",
  "photos": ["https://i.com/4", "https://i.com/5"],
  "premium": true,
  "favorite": false,
  "rating": 3,
  "housingType": "Room",
  "roomCount": 2,
  "guestCount": 2,
  "price": 2000,
  "conveniences": ["Washer", "Towels"],
  "authorId": "634ef0047bd6c921c2820792",
  "coordinates": {"latitude": "53.550341", "longitude": "4.895168"}
}

###

# Пользователи
## Регистрация пользователя

POST http://localhost:9000/users/register HTTP/1.1
Content-Type: application/json

{
  "userName": "Alice",
  "email": "mail@mail.local",
  "avatarPath": "ava2.jpg",
  "password": "qwerty",
  "userStatus": "Common"
}

###

## Авторизация пользователя

POST http://localhost:9000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "mail@mail.local",
  "password": "qwerty"
}

###

## Проверка статуса авторизации пользователя

GET http://localhost:9000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "mail@mail.local"
}

###
# Избранное
## Добавление предложения в избранное пользователя

POST http://localhost:9000/favorite/6353af951d882a3a15cb4313/635437867c638b6bb53169f2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer sometoken

###
## Удаление предложения из избранного пользователя

DELETE http://localhost:9000/favorite/6353af951d882a3a15cb4313/634ef0047bd6c921c28207a6 HTTP/1.1
Content-Type: application/json
Authorization: Bearer sometoken
###
## Получение избранного по id пользователя

GET http://localhost:9000/favorite/634ef0047bd6c921c282078b
Content-Type: application/json
Authorization: Bearer sometoken

###
# Комментарии
## Получение комментариев по id предложения
GET http://localhost:9000/offers/634ef0057bd6c921c28207be/comments HTTP/1.1
Content-Type: application/json

###
## Добавление комментария к предложению
POST http://localhost:9000/offers/634ef0047bd6c921c2820794/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer sometoken

{
  "offerId": "634ef0057bd6c921c28207be",
  "text": "Lorem ipsum",
  "rating": 2
}

###

## Отправка аватарки пользователю

POST http://localhost:9000/users/634ef0047bd6c921c282078b/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="1.png"
Content-Type: image/png

< Projects/1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

